import i18n from "i18next";
import { initReactI18next } from "react-i18next";

// the translations
// (tip move them in a JSON file and import them,
// or even better, manage them separated from your code: https://react.i18next.com/guides/multiple-translation-files)
const resources = {
    // en: {
    //     translation: {
    //         "WelcomeMessage": "Welcome to React and react-i18next"
    //     }
    // },
    // fr: {
    //     translation: {
    //         "WelcomeMessage": "Bienvenue à React et react-i18next"
    //     }
    // },
    es: {
        translation: {
            "WelcomeMessage_one": "Bienvenido a React y react-i18next. Tienes {{count}} notificación",
            "WelcomeMessage_other": "Bienvenido a React y react-i18next. Tienes {{count}} notificaciones",

            // Settings page
            "AppSettings": "Configuración de la aplicación",
            "LanguageSettings": "Preferencias de idioma",
            "ChooseLanguage": "Selecciona tu idioma preferido",
            "Spanish": "Español",
            "Catalan": "Catalán",
            "EmailNotifications": "Notificaciones por correo electrónico",
            "EmailUpdates": "Actualizaciones por correo electrónico",
            "EmailUpdatesDesc": "Recibe actualizaciones sobre el estado de tus servicios por correo electrónico",
            "PushNotifications": "Notificaciones por dispositivo",
            "DeviceNotifications": "Notificaciones por dispositivo",
            "DeviceNotificationsDesc": "Recibe notificaciones sobre el estado de tus servicios en el dispositivo",
            "AppUpdates": "Actualizaciones de la aplicación",
            "ProductUpdates": "Actualizaciones de producto",
            "ProductUpdatesDesc": "Recibe actualizaciones sobre nuevos productos y servicios",
            "Cuenta": "Cuenta",
            'Notificaciones': 'Notificaciones',
            'Seguridad': 'Seguridad',
            "AccountSecurity": "Seguridad de la cuenta",
            "TwoFactorAuth": "Autenticación de dos factores",
            "TwoFactorAuthDesc": "Activa la autenticación de dos factores para mayor seguridad",

            "SessionManagement": "Gestión de sesiones",
            "SessionTimeout": "Tiempo de espera de la sesión",
            "SessionTimeoutDesc": "Establece el tiempo de espera de la sesión antes de cerrarla automáticamente",
            "Minutes": "Minutos",
            "Hour": "Hora",
            "Hours": "Horas",
            "Day": "Día",

            "PasswordSecurity": "Seguridad de la contraseña",
            "ChangePassword": "Cambiar contraseña",
            "LastPasswordChange": "Último cambio de contraseña",

            // Home page
            "MainPanel": "Panel Principal",
            "RequestAssistance": "Solicitud asistencia",
            "RequestAssistanceDesc": "Solicita asistencia técnica para tus equipos",
            "ViewServices": "Mis servicios",
            "ViewServicesDesc": "Consulta el estado de tus servicios activos",
            "SATS": "SATS",
            "SATSDesc": "Gestiona el Sistema de Atención Técnica",
            "FiscalData": "Datos fiscales",
            "FiscalDataDesc": "Administra tu información fiscal",
            "Billing": "Facturación",
            "BillingDesc": "Gestiona tus facturas y pagos",
            "StartTour": "Iniciar Tour",
            // Navbar translations
            "Home": "Inicio",
            "AssistanceServices": "Solicitud asistencia",
            "MyServices": "Mis servicios",
            "RepairService": "Solicitud reparación",
            "InstallationService": "Solicitud instalación",
            "SaleService": "Solicitud venta",
            "WarrantyService": "Solicitud garantía",
            "User": "Usuario",
            "WelcomeTo": "Bienvenido a",
            "TechnicalService": "Servicio Técnico Integral",
            // Assistance page translations
            "AssistanceRequest": "Solicitud asistencia",
            "AssistanceType": "Tipo de Asistencia",
            "RepairRequest": "Nueva Reparación",
            "RepairDesc": "Solicita asistencia técnica para una reparación de tus equipos",
            "InstallationRequest": "Nueva Instalación",
            "InstallationDesc": "Programa la instalación profesional de tu nuevo equipo",
            "SaleRequest": "Nueva Venta",
            "SaleDesc": "Gestiona la venta y adquisición de nuevos equipos",
            "WarrantyRequest": "Nueva Garantía",
            "WarrantyDesc": "Tramita servicios cubiertos por la garantía de tu equipo",

            // Solicitud de asistencia page translations
            "RequestRepair": "Solicitar Reparación",
            "RequestInstallation": "Solicitar Instalación",
            "RequestQuote": "Solicitar Presupuesto",
            "RequestWarranty": "Solicitud asistencia en Garantía",
            "SuccessMessage": "Sus datos se han enviado con éxito, en la mayor brevedad posible llamaremos al cliente para citar la asistencia.",
            "BackToRepair": "Volver a Solicitar Reparación",
            "BackToInstallation": "Volver a Solicitar Instalación",
            "BackToSale": "Volver a Solicitar una venta",
            "BackToWarranty": "Volver a Solicitar una garantía",
            "WarrantyServiceRequest": "Solicitud de Asistencia en Garantía",
            "RepairServiceRequest": "Solicitud de Reparación",
            "InstallationServiceRequest": "Solicitud de Instalación",
            "SaleServiceRequest": "Solicitud de Venta",
            "Error": "Error",
            "ErrorMessage": "Hubo un problema al enviar su solicitud. Por favor, inténtelo de nuevo más tarde.",
            "RequestSent": "Solicitud enviada",

            "Repair": "Reparación",
            "Installation": "Instalación",
            "Sale": "Venta",
            "Warranty": "Garantía",

            // Service Form translations
            "ServiceAddress": "Dirección asistencia",
            "Phone": "Teléfono",
            "Name": "Nombre",
            "Surname": "Apellido",
            "SecondSurname": "Segundo Apellido",
            "Address": "Dirección",
            "FloorDoor": "Piso y puerta",
            "ZipCode": "Código Postal",
            "City": "Población",
            "Email": "Email",
            "EquipmentData": "Datos del equipo",
            "Brand": "Marca",
            "Equipment": "Aparato",
            "Model": "Modelo",
            "WarrantyEquipment": "Equipo en garantía",
            "SATPhone": "Teléfono SAT",
            "InvoiceNumber": "Número de Factura",
            "PurchaseDate": "Fecha de Compra",
            "AttachInvoice": "Adjuntar factura",
            "AcceptedFormats": "Formatos aceptados: JPG, PNG, PDF. Tamaño máximo: 5MB",
            "AddComment": "Añadir comentario",
            "FailureCommentary": "Descripción del fallo",
            "MaxCharacters": "Máximo 500 caracteres",
            "Characters": "caracteres",
            "SearchPlaceholder": "Escriba al menos 3 caracteres para buscar",
            "BrandPlaceholder": "Samsung, LG, etc.",
            "EquipmentPlaceholder": "Lavadora, Frigorifico, etc.",
            "BrandInfo": "Información marca",
            "BrandInfoDesc": "Aquí puedes encontrar la etiqueta de información de la marca.",
            "EquipmentInfo": "Información etiqueta",
            "EquipmentInfoDesc": "Aquí puedes ver dónde encontrar la etiqueta de información del aparato.",
            "ContactSupport": "Si no encuentras la etiqueta, por favor contacta con el servicio de atención al cliente.",
            "Device": "Aparato",
            "IsDeviceUnderWarranty": "¿El aparato está en garantía?",
            "WarrantyInfo": "Información importante sobre la garantía de tu electrodoméstico",
            "ExtendedLegalWarranty": "Garantía legal ampliada",
            "WarrantyLegalExtended": "Desde el 1 de enero de 2022, todos los electrodomésticos y bienes duraderos cuentan con 3 años de garantía legal.",
            "WarrantyDuration": "3 años",
            "WarrantyDurationDesc": "Garantía legal para productos desde 2022",
            "WarrantyDuration10Years": "10 años",
            "WarrantyDuration10YearsDesc": "Disponibilidad mínima de piezas de repuesto",
            "WarrantyDurationInvoice": "Siempre se deberá presentar la factura de adquisición del producto para su garantía.",
            "WarrantyInfoDesc2": "Si tienes cualquier duda sobre la garantía de tu electrodoméstico, nuestro servicio de atención al cliente está disponible para ayudarte.",
            "customer-comment": "Añade cualquier comentario adicional que consideres relevante para la asistencia.",

            "Back": "Volver",

            // Validation error messages
            "ValidationErrors": {
                "NameRequired": "El nombre es requerido",
                "SurnameRequired": "El apellido es requerido",
                "PhoneLength": "El teléfono debe tener al menos 9 dígitos",
                "PhoneFormat": "El teléfono solo debe contener números",
                "AddressRequired": "La dirección es requerida",
                "FloorDoorRequired": "El piso y puerta son requeridos",
                "ZipCodeLength": "El código postal debe tener 5 dígitos",
                "ZipCodeFormat": "El código postal solo debe contener números",
                "EmailInvalid": "El email no es válido",
                "DeviceRequired": "El aparato es requerido",
                "CommentLength": "El comentario no puede exceder los 500 caracteres",
                "SATPhoneLength": "El teléfono SAT debe tener al menos 9 dígitos",
                "SATPhoneFormat": "El teléfono SAT solo debe contener números",
                "InvoiceNumberRequired": "El número de factura es requerido",
                "PurchaseDateRequired": "La fecha de compra es requerida",
                "InvoiceRequired": "La factura es requerida",
                "FileSizeLimit": "El archivo no puede superar los 5MB",
                "FileTypeAccepted": "Solo se aceptan archivos JPG, PNG o PDF"
            },

            // Summary page translations
            "MyServices": "Mis servicios",
            "ClearFilters": "Limpiar filtros",
            "Status": "Estado",
            "AllStatuses": "Todos los estados",
            "InProcess": "En proceso",
            "Finished": "Finalizado",
            "Charged": "Cobrado",
            "Canceled": "Anulado",
            "ServiceType": "Tipo de servicio",
            "AllServices": "Todos los servicios",
            "SearchByNameOrPhone": "Buscar por nombre o teléfono...",
            "SelectCustomer": "Seleccionar cliente",
            "NoCustomerFound": "No se encontró ningún cliente",
            "NoNoticesAvailable": "No hay avisos disponibles.",
            "AllNotices": "Todos los Avisos",
            "NoNoticesFor": "No hay avisos de",
            "Date": "Fecha",
            "Customer": "Cliente",
            "Equipment": "Aparato",
            "Status": "Estado",
            "Observations": "Observaciones",
            "NumberCopied": "Número copiado",
            "NumberCopiedMessage": "El número {{number}} ha sido copiado al portapapeles.",
            "TheNumber": "El número",
            "hasBeenCopied": "ha sido copiado al portapapeles.",

            // Module titles
            "Overview": "Vista general",
            "ToContact": "Por contactar",
            "Contacted": "Contactados",
            "Scheduled": "Citados",
            "InProgress": "En proceso",
            "Completed": "Finalizados",

            // Calendar translations
            "SelectDate": "Selecciona una fecha",

            // SAT page translations
            "SATDirectory": "SATS",
            "SearchBrand": "Buscar marca...",
            "BackToList": "Volver a la lista",
            "MainContacts": "Contactos principales",
            "Websites": "Sitios Web",
            "Downloads": "Descargas",
            "ImportantInfo": "Información importante",
            "ImportantInfoDesc": "Esta información es orientativa y puede estar sujeta a cambios. Siempre verifique los procedimientos actuales con el fabricante o distribuidor.",
            "NoSATResults": "No se encontraron marcas que coincidan con la búsqueda",
            "TryAnotherSearch": "Prueba otra búsqueda",
            "ScrollToTop": "Volver arriba",
            "Contacts": "Contactos",
            MoreContacts_one: "{{count}} contacto más",
            MoreContacts_other: "{{count}} contactos más",

            // NavProfileUser translations
            "Administrator": "Administrador",
            "User": "Usuario",
            "Billing": "Facturación",
            "FiscalData": "Datos fiscales",
            "AddBusiness": "Añadir negocio",
            "AddUser": "Añadir usuario",
            "Profile": "Perfil",
            "SuperAdmin": "Super Admin",
            "Settings": "Configuración",
            "LogOut": "Cerrar sesión",

            // Theme translations
            "Theme": "Tema",
            "Light": "Claro",
            "Dark": "Oscuro",

            // Billing page translations
            "Billing": "Facturación",
            "ActiveFilter": "Filtro activo",
            "ClickToClearFilter": "Haga clic para eliminar el filtro",
            "RestrictedAccess": "Acceso Restringido",
            "NoAdminPermissions": "No tienes permisos de administrador para ver o editar los datos de facturación",
            "BillingDataAdminOnly": "Los datos de facturación solo pueden ser gestionados por usuarios administradores. Si necesitas información de los datos de facturación, por favor contacta con un administrador del sistema.",
            "ContactSupport": "Para más información o asistencia, puedes contactar con el equipo de soporte.",
            "LeadsInProcess": "Avisos en Proceso",
            "AccumulatedLeads": "Avisos Acumulados",
            "BilledLeads": "Avisos Cobrados",
            "CancelledLeads": "Avisos Cancelados",
            "Value": "Valor",
            "Leads_one": "Aviso",
            "Leads_other": "Avisos",
            "NoticesDateRange": "Avisos {{from}} {{to}}",
            "CollaboratorBonuses": "Bonificaciones colaborador",
            "BonusTableDescription": "Tabla de bonificaciones según el volumen de avisos",
            "PriceTable": "Tabla de precio",
            "Volume": "Volumen",
            "RepairLeads": "Avisos reparación",
            "InstallationLeads": "Avisos instalación",
            "ClimateMaintenanceLeads": "Led del conexión o mantenimiento clima",
            "BillingProcess": "Proceso de Facturación",
            "BillingProcessDescription": "El proceso de facturación se realiza automáticamente los días 15 y 30 de cada mes",
            "LeadsBilling": "Cobro de avisos",
            "BillingDates": "Se realiza los días 15 y 30 de cada mes",
            "AutomaticInvoiceGeneration": "Emisión de factura automática",
            "GeneratedAfterBilling": "Se genera después del cobro",
            "TransferIssuance": "Emisión de transferencia",
            "ProcessedAfterBilling": "Se procesa tras la facturación",
            "NoResults": "No hay avisos que coincidan con los criterios de búsqueda.",

            // Fiscal Data page translations
            "FiscalData": "Datos fiscales",
            "CancelEditing": "Cancelar edición",
            "EditData": "Editar datos",
            "FiscalDataMatchWarning": "Los datos fiscales deberán coincidir con los documentos de la empresa",
            "DataUpdated": "Datos actualizados",
            "Error": "Error",
            "ErrorFetchingFiscalData": "Error al obtener los datos fiscales",
            "RestrictedAccess": "Acceso Restringido",
            "NoAdminPermissionsFiscal": "No tienes permisos de administrador para ver o editar los datos fiscales",
            "FiscalDataAdminOnly": "Los datos fiscales solo pueden ser gestionados por usuarios administradores. Si necesitas realizar cambios en la información fiscal, por favor contacta con un administrador del sistema.",
            "ContactSupport": "Para más información o asistencia, puedes contactar con el equipo de soporte.",

            // Fiscal Data Form translations
            "Type": "Tipo",
            "SelectType": "Seleccione el tipo",
            "Company": "Empresa",
            "SelfEmployed": "Autónomo",
            "DocumentType": "Tipo documento",
            "SelectDocumentType": "Seleccione el tipo de documento",
            "FiscalNumber": "Número fiscal",
            "FiscalName": "Nombre fiscal",
            "CommercialName": "Nombre comercial",
            "Name": "Nombre",
            "FirstSurname": "1º Apellido",
            "SecondSurname": "2º Apellido",
            "Address": "Dirección",
            "PostalCode": "Código postal",
            "City": "Ciudad",
            "Province": "Provincia",
            "MobilePhone": "Teléfono móvil",
            "LandlinePhone": "Teléfono fijo",
            "Email": "Correo electrónico",
            "IBAN": "IBAN",
            "SaveChanges": "Guardar cambios",
            "ContactPerson1": "Persona contacto 1",
            "ErrorUpdatingData": "Error al actualizar los datos",
            "Contacts": "Contactos",
            "ContactPerson1Description": "Listado de contactos de la empresa",

            // Super Admin
            "loading": "Cargando...",
            "customers": "Clientes",
            "notices": "Avisos",
            "PendingPayments": "Pagos Pendientes",
            "SuperAdminAccess": "Acceso SuperAdmin",
            "PanelSuperAdmin": "Panel SuperAdmin",
            "Lastnotices": "Últimos 10 avisos",
            "Contact": "Contacto",
            "Location": "Ubicación",
            "Created": "Fecha de alta",
            "Balance": "Saldo",
            "Actions": "Acciones",
            "TotalCustomers": "Clientes Totales",
            "TotalNotices": "Avisos totales",
            "TotalInvoiced": "Total Facturado",
            active_one: "{{count}} activo",
            active_other: "{{count}} activos",
            inactive_one: "{{count}} inactivos",
            inactive_other: "{{count}} inactivos",
            "ToProcess": "Por procesar",
            "ThisMonth": "Este mes",


            // New Business Page
            "NewBusinessRegistration": "Registro de nuevo negocio",
            "FillFormNewBusiness": "Rellene el formulario para crear una nueva cuenta",

            "Warning": "¡Atención!",
            "AdminOnlyNewUsers": "Solo los administradores pueden crear nuevos usuarios.",
            "ErrorRegisteringBusiness": "Error al registrar el nuevo negocio",
            "SuccessfulRegistration": "Registro exitoso",
            "RegistrationEmailSent": "Le hemos enviado un correo para confirmar y validar su contraseña. Por favor revise su bandeja de entrada o spam.",
            "ErrorCreatingAccount": "Ocurrió un error al registrar la cuenta.",

            // New User Page
            "NewUserRegistration": "Registro de nuevo usuario",
            "FillFormNewAccount": "Complete el formulario para crear una nueva cuenta de usuario.",
            "OnlyAdministratorsCanCreateUsers": "Solo los administradores pueden crear nuevos usuarios.",

            // Register Form
            "UserType": "Tipo de usuario",
            "SelectUserType": "Selecciona el tipo de usuario",
            "BusinessType": "Empresa",
            "SelfEmployedType": "Autónomo",
            "DocumentType": "Tipo de documento",
            "SelectDocument": "Selecciona...",
            "FiscalId": "Identificador fiscal",
            "CompanyName": "Nombre compañía",
            "CommercialName": "Nombre comercial",
            "MobilePhone": "Móvil",
            "LandlinePhone": "Teléfono",
            "Password": "Contraseña",
            "ConfirmPassword": "Confirmar Contraseña",
            "RequiredFields": "* Campos obligatorios",
            "CreatingAccount": "Creando cuenta...",
            "CreateAccount": "Crear cuenta",
            "HidePassword": "Ocultar contraseña",
            "ShowPassword": "Mostrar contraseña",
            "Login": "Inicia sesión",
            "CopyPasteDisabled": "No se permite copiar y pegar",
            "CopyPasteDisabledDescription": "La función de copiar y pegar está deshabilitada por razones de seguridad. Por favor, ingresa la información manualmente.",
            "ConfirmEmail": "Confirmar correo electrónico",

            "Processing": "Procesando...",

            // Page Titles
            "HomePage": "Inicio",
            "AssistancePage": "Asistencia",
            "ReparationPage": "Reparación",
            "InstallationPage": "Instalación",
            "ResumenPage": "Resumen",
            "FacturationPage": "Facturación",
            "FiscalData": "Datos Fiscales",
            "SuperAdminPanel": "Panel SuperAdmin",
            "NewBusiness": "Nuevo Negocio",
            "NewUser": "Nuevo Usuario",
            "Settings": "Configuración",
            "RecoverPassword": "Recuperar Contraseña",
            "Register": "Registro",

            // Tour HOME
            "first-step": "Bienvenido al tutorial de nuestra aplicación. Aquí aprenderás a crear un aviso desde cero y a utilizar todas las funcionalidades de la aplicación.",
            "second-step": "En esta sección podrás crear un aviso desde cero.",
            "third-step": "Aquí podrás ver todos los avisos que has creado y su estado.",
            "fourth-step": "En esta sección podrás obtener información sobre los servicios técnicos de las marcas con las que solemos trabajar.",
            "fifth-step": "En datos fiscales podrás editar tus datos personales y los datos de tu empresa.",
            "sixth-step": "La sección de facturación te permitirá ver los avisos que has creado, su estado y la conversión económica de los mismos.",

            // Tour ASSISTANCE
            "asistencia-header": "Esta es la sección de asistencia donde podrás solicitar diferentes tipos de servicios.",
            "repair-module": "Aquí puedes solicitar una reparación para tus electrodomésticos.",
            "installation-module": "En esta sección puedes programar la instalación de nuevos equipos.",

            // Tour SERVICE FORM
            "warranty-question": "Primero, necesitamos saber si tu equipo está en garantía para ofrecerte el mejor servicio.",
            "warranty-yes": "Si el equipo está en garantía, selecciona esta opción.",
            "warranty-no": "Si el equipo no está en garantía, selecciona esta opción.",
            "service-address": "Aquí puedes ingresar los datos de contacto y la dirección donde se realizará el servicio.",
            "customer-phone": "Si tenemos el teléfono del cliente en nuestra base de datos, los datos se completarán automáticamente.",
            "equipment-data": "En esta sección, proporciona los detalles de tu electrodoméstico.",
            "brand-selector": "Selecciona la marca de tu electrodoméstico. ",
            "device-selector": "Selecciona el tipo de electrodoméstico que necesitas reparar o instalar. Esto nos ayuda a asignar el técnico más adecuado.",
            "model-input": "Ingresa el modelo específico del electrodoméstico a reparar.",
            "comment-section": "Describe el problema o servicio que necesitas. Cuantos más detalles proporciones, mejor podremos ayudarte.",
            "submit-button": 'Una vez que hayas completado todos los campos, haz clic en "Enviar" para crear la solicitud.',
            "back-button": 'Si deseas volver a la página anterior, haz clic en "Volver".',
            "sat-information": 'Aquí puedes encontrar información sobre la garantía de tu electrodoméstico. Puedes usar el buscador para encontrar la marca de tu equipo.',
            "select-brand": "Selecciona la marca de tu electrodoméstico para ver la información de contacto del servicio técnico.",


            // TOUR SET STEPS
            "sat-header": "En esta sección podrás ver la información de los servicios técnicos de las marcas con las que trabajamos.",
            "sat-search": "Aquí puedes buscar una marca específica.",
            "brand-info": "Haz clic en una marca para ver más información sobre su servicio técnico.",
            "sat-info": "Aquí podrás ver la información de contacto del servicio técnico de la marca seleccionada.",
            "back-button": 'Si deseas volver a la página anterior, haz clic en "Volver".',

            // Tour Facturación steps
            "facturacion-header": "En esta sección podrás ver la información sobre la facturación de tus avisos.",
            "calendar-filter": "Aquí puedes filtrar los avisos por fecha.",
            "cards-filter": "Al hacer click en las tarjetas, podrás ver más información sobre los avisos, su estado y filtrar los avisos de la tabla.",
            "accumulated-card": "Por ejemplo, aquí podrás ver la información sobre la facturación acumulada de tus avisos.",
            "dialog-info": "En el dialogo podrás ver la información detallada de los avisos.",
            "monedero-info": "Aquí podrás ver la información sobre el saldo de tu monedero.",


            // Tour Fiscal Data steps
            "fiscal-data-header": "En esta sección podrás ver y editar los datos fiscales de tu empresa.",
            "fiscal-data-edit-button": "Haz clic aquí para editar los datos fiscales de tu empresa o cancelar la edición",
            "fiscal-data-form": "Después de hacer clic en editar, podrás editar los datos fiscales de tu empresa.",
            "fiscal-data-submit": "Haz clic aquí para guardar los cambios realizados en los datos fiscales.",
            "fiscal-data-contact-button": "Aquí podrás ver los contactos de tu empresa.",


            // Tour Resumen steps
            "resumen-header": "En esta sección podrás ver el resumen de tus avisos.",
            "calendar-filter": "Aquí puedes filtrar los avisos por fecha.",
            "date-picker": "Puedes seleccionar un rango de fechas o del mismo día clicando 2 veces en la fecha requerida.",
            "status-filter": "Aquí puedes filtrar los avisos por estado.",
            "service-type": "Aquí puedes filtrar los avisos por tipo de servicio.",
            "customer-name-filter": "Aquí puedes buscar un cliente creado por tí por su nombre o teléfono.",
            "clean-filter": "Si deseas limpiar los filtros, haz clic aquí.",

            // Tour ADD BusINESS steps
            "add-business-header": "En esta sección podrás registrar un nuevo negocio.",
            "add-business-submit": "Haz clic aquí para enviar el formulario y registrar el nuevo negocio.",

            // Tour ADD USER steps
            "add-user-header": "En esta sección podrás registrar un nuevo usuario.",
            "add-user-submit": "Haz clic aquí para enviar el formulario y registrar el nuevo usuario.",

            // Error messages
            "NetworkErrorTitle": "Error de red",

        }
    },
    cat: {
        translation: {
            "WelcomeMessage_one": "Benvingut a React i react-i18next. Tens {{count}} notificació",
            "WelcomeMessage_other": "Benvingut a React i react-i18next. Tens {{count}} notificacions",
            // Settings page
            "AppSettings": "Configuració de l'aplicació",
            "LanguageSettings": "Preferències d'idioma",
            "ChooseLanguage": "Selecciona el teu idioma preferit",
            "Spanish": "Espanyol",
            "Catalan": "Català",
            "EmailNotifications": "Notificacions per correu electrònic",
            "EmailUpdates": "Actualitzacions per correu electrònic",
            "EmailUpdatesDesc": "Rep actualitzacions sobre l'estat dels teus serveis per correu electrònic",
            "PushNotifications": "Notificacions per dispositiu",
            "DeviceNotifications": "Notificacions per dispositiu",
            "DeviceNotificationsDesc": "Rep notificacions sobre l'estat dels teus serveis al dispositiu",
            "AppUpdates": "Actualitzacions de l'aplicació",
            "ProductUpdates": "Actualitzacions de producte",
            "ProductUpdatesDesc": "Rep actualitzacions sobre nous productes i serveis",
            'Cuenta': 'Compte',
            'Notificaciones': 'Notificacions',
            'Seguridad': 'Seguretat',
            "AccountSecurity": "Seguretat del compte",
            "TwoFactorAuth": "Autenticació de dos factors",
            "TwoFactorAuthDesc": "Activa l'autenticació de dos factors per a una major seguretat",

            "SessionManagement": "Gestió de sessions",
            "SessionTimeout": "Temps d'espera de la sessió",
            "SessionTimeoutDesc": "Estableix el temps d'espera de la sessió abans de tancar-la automàticament",
            "Minutes": "Minuts",
            "Hour": "Hora",
            "Hours": "Hores",
            "Day": "Dia",


            "PasswordSecurity": "Seguretat de la contrasenya",
            "ChangePassword": "Canviar contrasenya",
            "LastPasswordChange": "Últim canvi de contrasenya",


            // Home page
            "MainPanel": "Panell Principal",
            "RequestAssistance": "Sol·licitar una nova assistència",
            "RequestAssistanceDesc": "Sol·licita assistència tècnica per als teus equips",
            "ViewServices": "Els meus serveis",
            "ViewServicesDesc": "Consulta l'estat dels teus serveis actius",
            "SATS": "SATS",
            "SATSDesc": "Gestiona el Sistema d'Atenció Tècnica",
            "FiscalData": "Dades fiscals",
            "FiscalDataDesc": "Administra la teva informació fiscal",
            "Billing": "Facturació",
            "BillingDesc": "Gestiona les teves factures i pagaments",
            "StartTour": "Començar Tour",

            // Navbar translations
            "Home": "Inici",
            "AssistanceServices": "Sol·licitud assistència",
            "MyServices": "Els meus serveis",
            "RepairService": "Sol·licitud reparació",
            "InstallationService": "Sol·licitud instal·lació",
            "SaleService": "Sol·licitud venda",
            "WarrantyService": "Sol·licitud garantia",
            "User": "Usuari",
            "WelcomeTo": "Benvingut a",
            "TechnicalService": "Servei Tècnic Integral",
            // Assistance page translations
            "AssistanceRequest": "Sol·licitud d'Assistència",
            "AssistanceType": "Tipus d'Assistència",
            "RepairRequest": "Nova Reparació",
            "RepairDesc": "Sol·licita assistència tècnica per a una reparació dels teus equips",
            "InstallationRequest": "Nova Instal·lació",
            "InstallationDesc": "Programa la instal·lació professional del teu nou equip",
            "SaleRequest": "Nova Venda",
            "SaleDesc": "Gestiona la venda i adquisició de nous equips",
            "WarrantyRequest": "Nova Garantia",
            "WarrantyDesc": "Tramita serveis coberts per la garantia del teu equip",
            // Solicitud de asistencia page translations
            "RequestRepair": "Sol·licitar Reparació",
            "RequestInstallation": "Sol·licitar Instal·lació",
            "RequestQuote": "Sol·licitar Pressupost",
            "RequestWarranty": "Sol·licitar Assistència en Garantia",
            "SuccessMessage": "Les teves dades s'han enviat amb èxit, en la major brevetat possible trucarem al client per citar l'assistència.",
            "BackToRepair": "Tornar a Sol·licitar Reparació",
            "BackToInstallation": "Tornar a Sol·licitar Instal·lació",
            "BackToSale": "Tornar a Sol·licitar una venda",
            "BackToWarranty": "Tornar a Sol·licitar una garantia",
            "WarrantyServiceRequest": "Sol·licitud d'Assistència en Garantia",
            "RepairServiceRequest": "Sol·licitud de Reparació",
            "InstallationServiceRequest": "Sol·licitud d'Instal·lació",
            "SaleServiceRequest": "Sol·licitud de Venda",
            "Error": "Error",
            "ErrorMessage": "Hi ha hagut un problema en enviar la seva sol·licitud. Si us plau, intenti-ho de nou més tard.",
            "RequestSent": "Sol·licitud enviada",

            "Repair": "Reparació",
            "Installation": "Instal·lació",
            "Sale": "Venda",
            "Warranty": "Garantia",

            // Service Form translations
            "ServiceAddress": "Adreça assistència",
            "Phone": "Telèfon",
            "Name": "Nom",
            "Surname": "Cognom",
            "SecondSurname": "Segon Cognom",
            "Address": "Adreça",
            "FloorDoor": "Pis i porta",
            "ZipCode": "Codi Postal",
            "City": "Població",
            "Email": "Correu electrònic",
            "EquipmentData": "Dades de l'equip",
            "Brand": "Marca",
            "Equipment": "Aparell",
            "Model": "Model",
            "WarrantyEquipment": "Equip en garantia",
            "SATPhone": "Telèfon SAT",
            "InvoiceNumber": "Número de Factura",
            "PurchaseDate": "Data de Compra",
            "AttachInvoice": "Adjuntar factura",
            "AcceptedFormats": "Formats acceptats: JPG, PNG, PDF. Mida màxima: 5MB",
            "AddComment": "Afegir comentari (opcional)",
            "FailureCommentary": "Descripció del problema",
            "MaxCharacters": "Màxim 500 caràcters",
            "Characters": "caràcters",
            "SearchPlaceholder": "Escriu almenys 3 caràcters per cercar",
            "BrandPlaceholder": "Samsung, LG, etc.",
            "EquipmentPlaceholder": "Rentadora, Nevera, etc.",
            "BrandInfo": "Informació marca",
            "BrandInfoDesc": "Aquí pots trobar l'etiqueta d'informació de la marca.",
            "EquipmentInfo": "Informació etiqueta",
            "EquipmentInfoDesc": "Aquí pots veure on trobar l'etiqueta d'informació de l'aparell.",
            "ContactSupport": "Si no trobes l'etiqueta, si us plau contacta amb el servei d'atenció al client.",
            "Device": "Dispositiu",
            "IsDeviceUnderWarranty": "L'aparell està en garantia?",
            "WarrantyInfo": "Informació important sobre la garantia del teu electrodomèstic",
            "ExtendedLegalWarranty": "Garantia legal ampliada",
            "WarrantyLegalExtended": "Des del 1 de gener de 2022, tots els electrodomèstics i béns duradors compten amb 3 anys de garantia legal.",
            "WarrantyDuration": "3 anys",
            "WarrantyDurationDesc": "Garantia legal per a productes des de 2022",
            "WarrantyDuration10Years": "10 anys",
            "WarrantyDuration10YearsDesc": "Disponibilitat mínima de peces de recanvi",
            "WarrantyDurationInvoice": "Sempre s'haurà de presentar la factura d'adquisició del producte per a la seva garantia.",
            "WarrantyInfoDesc2": "Si tens qualsevol dubte sobre la garantia del teu electrodomèstic, el nostre servei d'atenció al client està disponible per ajudar-te.",
            "customer-comment": "Afegiu qualsevol comentari addicional que considereu rellevant per a l'assistència.",


            "Back": "Tornar",

            // Validation error messages
            "ValidationErrors": {
                "NameRequired": "El nom és obligatori",
                "SurnameRequired": "El cognom és obligatori",
                "PhoneLength": "El telèfon ha de tenir almenys 9 dígits",
                "PhoneFormat": "El telèfon només ha de contenir números",
                "AddressRequired": "L'adreça és obligatòria",
                "FloorDoorRequired": "El pis i porta són obligatoris",
                "ZipCodeLength": "El codi postal ha de tenir 5 dígits",
                "ZipCodeFormat": "El codi postal només ha de contenir números",
                "EmailInvalid": "El correu electrònic no és vàlid",
                "DeviceRequired": "L'aparell és obligatori",
                "CommentLength": "El comentari no pot excedir els 500 caràcters",
                "SATPhoneLength": "El telèfon SAT ha de tenir almenys 9 dígits",
                "SATPhoneFormat": "El telèfon SAT només ha de contenir números",
                "InvoiceNumberRequired": "El número de factura és obligatori",
                "PurchaseDateRequired": "La data de compra és obligatòria",
                "InvoiceRequired": "La factura és obligatòria",
                "FileSizeLimit": "L'arxiu no pot superar els 5MB",
                "FileTypeAccepted": "Només s'accepten arxius JPG, PNG o PDF"
            },

            // Summary page translations
            "MyServices": "Els meus serveis",
            "ClearFilters": "Netejar filtres",
            "Status": "Estat",
            "AllStatuses": "Tots els estats",
            "InProcess": "En procés",
            "Finished": "Finalitzat",
            "Charged": "Cobrat",
            "Canceled": "Anul·lat",
            "ServiceType": "Tipus de servei",
            "AllServices": "Tots els serveis",
            "SearchByNameOrPhone": "Cercar per nom o telèfon...",
            "SelectCustomer": "Seleccionar client",
            "NoCustomerFound": "No s'ha trobat cap client",
            "NoNoticesAvailable": "No hi ha avisos disponibles.",
            "AllNotices": "Tots els Avisos",
            "NoNoticesFor": "No hi ha avisos de",
            "Date": "Data",
            "Customer": "Client",
            "Equipment": "Aparell",
            "Status": "Estat",
            "Observations": "Observacions",
            "NumberCopied": "Número copiat",
            "NumberCopiedMessage": "El número {{number}} ha estat copiat al porta-retalls.",
            "TheNumber": "El número",
            "hasBeenCopied": "ha estat copiat al porta-retalls.",

            // Module titles
            "Overview": "Vista general",
            "ToContact": "Per contactar",
            "Contacted": "Contactats",
            "Scheduled": "Citats",
            "InProgress": "En procés",
            "Completed": "Finalitzats",

            // Calendar translations
            "SelectDate": "Selecciona una data",

            // SAT page translations
            "SATDirectory": "SATS",
            "SearchBrand": "Cercar marca...",
            "BackToList": "Tornar a la llista",
            "MainContacts": "Contactes principals",
            "Websites": "Llocs Web",
            "Downloads": "Descàrregues",
            "ImportantInfo": "Informació important",
            "ImportantInfoDesc": "Aquesta informació és orientativa i pot estar subjecta a canvis. Sempre verifiqueu els procediments actuals amb el fabricant o distribuïdor.",
            // "NoResults": "No s'han trobat marques que coincideixin amb",
            "NoSATResults": "No s'han trobat marques que coincideixin amb la cerca",
            "TryAnotherSearch": "Prova una altra cerca",
            "ScrollToTop": "Tornar amunt",
            "Contacts": "Contactes",
            MoreContacts_one: "{{count}} contacte més",
            MoreContacts_other: "{{count}} contactes més",

            // NavProfileUser translations
            "Administrator": "Administrador",
            "User": "Usuari",
            "Billing": "Facturació",
            "FiscalData": "Dades fiscals",
            "AddBusiness": "Afegir negoci",
            "AddUser": "Afegir usuari",
            "Profile": "Perfil",
            "SuperAdmin": "Super Admin",
            "Settings": "Configuració",
            "LogOut": "Tancar sessió",

            // Theme translations
            "Theme": "Tema",
            "Light": "Clar",
            "Dark": "Fosc",

            // Billing page translations
            "Billing": "Facturació",
            "ActiveFilter": "Filtre actiu",
            "ClickToClearFilter": "Feu clic per eliminar el filtre",
            "RestrictedAccess": "Accés Restringit",
            "NoAdminPermissions": "No tens permisos d'administrador per veure o editar les dades de facturació",
            "BillingDataAdminOnly": "Les dades de facturació només poden ser gestionades per usuaris administradors. Si necessites informació de les dades de facturació, si us plau contacta amb un administrador del sistema.",
            "ContactSupport": "Per a més informació o assistència, pots contactar amb l'equip de suport.",
            "LeadsInProcess": "Avisos en Procés",
            "AccumulatedLeads": "Avisos Acumulats",
            "BilledLeads": "Avisos Cobrats",
            "CancelledLeads": "Avisos Cancel·lats",
            "Value": "Valor",
            "Leads_one": "AVIS",
            "Leads_other": "AVISOS",
            "NoticesDateRange": "Avisos {{from}} {{to}}",
            "CollaboratorBonuses": "Bonificacions col·laborador",
            "BonusTableDescription": "Taula de bonificacions segons el volum d'avisos",
            "PriceTable": "Taula de preu",
            "Volume": "Volum",
            "RepairLeads": "Avisos reparació",
            "InstallationLeads": "Avisos instal·lació",
            "ClimateMaintenanceLeads": "Led de connexió o manteniment clima",
            "BillingProcess": "Procés de Facturació",
            "BillingProcessDescription": "El procés de facturació es realitza automàticament els dies 15 i 30 de cada mes",
            "LeadsBilling": "Cobrament d'avisos",
            "BillingDates": "Es realitza els dies 15 i 30 de cada mes",
            "AutomaticInvoiceGeneration": "Emissió de factura automàtica",
            "GeneratedAfterBilling": "Es genera després del cobrament",
            "TransferIssuance": "Emissió de transferència",
            "ProcessedAfterBilling": "Es processa després de la facturació",
            "NoResults": "No hi ha avisos que coincideixin amb els criteris de cerca.",

            // Fiscal Data page translations
            "FiscalData": "Dades fiscals",
            "CancelEditing": "Cancel·lar edició",
            "EditData": "Editar dades",
            "FiscalDataMatchWarning": "Les dades fiscals hauran de coincidir amb els documents de l'empresa",
            "DataUpdated": "Dades actualitzades",
            "Error": "Error",
            "ErrorFetchingFiscalData": "Error en obtenir les dades fiscals",
            "RestrictedAccess": "Accés Restringit",
            "NoAdminPermissionsFiscal": "No tens permisos d'administrador per veure o editar les dades fiscals",
            "FiscalDataAdminOnly": "Les dades fiscals només poden ser gestionades per usuaris administradors. Si necessites realitzar canvis en la informació fiscal, si us plau contacta amb un administrador del sistema.",
            "ContactSupport": "Per a més informació o assistència, pots contactar amb l'equip de suport.",

            // Fiscal Data Form translations
            "Type": "Tipus",
            "SelectType": "Seleccioneu el tipus",
            "Company": "Empresa",
            "SelfEmployed": "Autònom",
            "DocumentType": "Tipus document",
            "SelectDocumentType": "Seleccioneu el tipus de document",
            "FiscalNumber": "Número fiscal",
            "FiscalName": "Nom fiscal",
            "CommercialName": "Nom comercial",
            "Name": "Nom",
            "FirstSurname": "1r Cognom",
            "SecondSurname": "2n Cognom",
            "Address": "Adreça",
            "PostalCode": "Codi postal",
            "City": "Ciutat",
            "Province": "Província",
            "MobilePhone": "Telèfon mòbil",
            "LandlinePhone": "Telèfon fix",
            "Email": "Correu electrònic",
            "IBAN": "IBAN",
            "SaveChanges": "Desar canvis",
            "ContactPerson1": "Persona contacte 1",
            "ErrorUpdatingData": "Error en actualitzar les dades",
            "Contacts": "Contactes",
            "ContactPerson1Description": "Llistat de contactes de l'empresa",


            // Super Admin
            "loading": "Carregant...",
            "customers": "Clients",
            "notices": "Avisos",
            "PendingPayments": "Pagaments Pendents",
            "SuperAdminAccess": "Accés SuperAdmin",
            "PanelSuperAdmin": "Panell SuperAdmin",
            "Lastnotices": "Últims 10 avisos",
            "Contact": "Contacte",
            "Location": "Localització",
            "Created": "Data d'alta",
            "Balance": "Saldo",
            "Actions": "Accions",
            "TotalCustomers": "Clients Totals",
            "TotalNotices": "Total d'avisos",
            "TotalInvoiced": "Total Facturat",
            active_one: "{{count}} actiu",
            active_other: "{{count}} actius",
            inactive_one: "{{count}} inactiu",
            inactive_other: "{{count}} inactius",
            "ToProcess": "Per processar",
            "ThisMonth": "Aquest mes",

            // New Business Page
            "NewBusinessRegistration": "Registre de nou negoci",
            // "FillFormNewAccount": "Ompliu el formulari per crear un nou compte",
            "FillFormNewBusiness": "Ompliu el formulari per crear un nou compte",
            "Warning": "Atenció!",
            "AdminOnlyNewUsers": "Només els administradors poden crear nous usuaris.",
            "ErrorRegisteringBusiness": "Error en registrar el nou negoci",
            "SuccessfulRegistration": "Registre exitós",
            "RegistrationEmailSent": "Li hem enviat un correu per confirmar i validar la seva contrasenya. Si us plau revisi la seva safata d'entrada o spam.",
            "ErrorCreatingAccount": "Ha ocorregut un error en registrar el compte.",

            // New User Page
            "NewUserRegistration": "Registre de nou usuari",
            "FillFormNewAccount": "Ompliu el formulari per crear un nou compte d'usuari.",
            "OnlyAdministratorsCanCreateUsers": "Només els administradors poden crear nous usuaris.",

            // Register Form
            "UserType": "Tipus d'usuari",
            "SelectUserType": "Selecciona el tipus d'usuari",
            "BusinessType": "Empresa",
            "SelfEmployedType": "Autònom",
            "DocumentType": "Tipus de document",
            "SelectDocument": "Selecciona...",
            "FiscalId": "Identificador fiscal",
            "CompanyName": "Nom companyia",
            "CommercialName": "Nom comercial",
            "MobilePhone": "Mòbil",
            "LandlinePhone": "Telèfon",
            "Password": "Contrasenya",
            "ConfirmPassword": "Confirmar Contrasenya",
            "RequiredFields": "* Camps obligatoris",
            "CreatingAccount": "Creant compte...",
            "CreateAccount": "Crear compte",
            "HidePassword": "Ocultar contrasenya",
            "ShowPassword": "Mostrar contrasenya",
            "Login": "Inicia sessió",
            "CopyPasteDisabled": "No es permet copiar i enganxar",
            "CopyPasteDisabledDescription": "La funció de copiar i enganxar està deshabilitada per raons de seguretat. Si us plau, introdueix la informació manualment.",
            "ConfirmEmail": "Confirma el correu electrònic",

            "Processing": "Processant...",

            // Page Titles
            "HomePage": "Inici",
            "AssistancePage": "Assistència",
            "ReparationPage": "Reparació",
            "InstallationPage": "Instal·lació",
            "ResumenPage": "Resum",
            "FacturationPage": "Facturació",
            "FiscalData": "Dades Fiscals",
            "SuperAdminPanel": "Panell SuperAdmin",
            "NewBusiness": "Nou Negoci",
            "NewUser": "Nou Usuari",
            "Settings": "Configuració",
            "RecoverPassword": "Recuperar Contrasenya",
            "Register": "Registrar-se",

            // Tour HOME
            "first-step": "Benvingut al tutorial de la nostra aplicació. Aquí aprendràs a crear un avís des de zero i a utilitzar totes les funcionalitats de l'aplicació.",
            "second-step": "En aquesta secció podràs crear un avís des de zero.",
            "third-step": "Aquí podràs veure tots els avisos que has creat i el seu estat.",
            "fourth-step": "En aquesta módul podràs obtenir informació sobre els serveis tècnics de les marques amb les quals treballem.",
            "fifth-step": "En el módul de dades fiscals podràs editar les teves dades personals i les dades de la teva empresa.",
            "sixth-step": "La secció de facturació et permetrà veure els avisos que has creat, el seu estat i la conversió econòmica dels mateixos.",

            // Tour ASSISTANCE
            "asistencia-header": "Aquesta és la secció d'assistència on podràs sol·licitar diferents tipus de serveis.",
            "repair-module": "Aquí pots sol·licitar una reparació per als teus electrodomèstics.",
            "installation-module": "En aquesta secció pots programar la instal·lació de nous equips.",

            // Tour SERVICE FORM
            "warranty-question": "Primer, necessitem saber si el teu equip està en garantia per oferir-te el millor servei.",
            "warranty-yes": "Si l'equip està en garantia, selecciona aquesta opció.",
            "warranty-no": "Si l'equip no està en garantia, selecciona aquesta opció.",
            "service-address": "Aquí pots ingressar les dades de contacte i l'adreça on es realitzarà el servei.",
            "customer-phone": "Si tenim el telèfon del client a la nostra base de dades, les dades es completaran automàticament.",
            "equipment-data": "En aquesta secció, proporciona els detalls del teu electrodomèstic.",
            "brand-selector": "Selecciona la marca del teu electrodomèstic.",
            "device-selector": "Selecciona el tipus d'electrodomèstic que necessites reparar o instal·lar. Això ens ajuda a assignar el tècnic més adequat.",
            "model-input": "Introdueix el model específic de l'electrodomèstic a reparar.",
            "comment-section": "Descriu el problema o servei que necessites. Quants més detalls proporcionis, millor podrem ajudar-te.",
            "submit-button": 'Un cop hagis completat tots els camps, fes clic a "Enviar" per crear la sol·licitud.',
            "back-button": 'Si desitges tornar a la pàgina anterior, fes clic a "Tornar".',
            "sat-information": "Aquí pots trobar informació sobre la garantia del teu electrodomèstic. Pots utilitzar el cercador per trobar la marca del teu equip.",
            "select-brand": "Selecciona la marca del teu electrodomèstic per obtenir informació sobre la garantia.",

            // TOUR SET STEPS
            "sat-header": "En aquesta secció podràs veure la informació dels serveis tècnics de les marques amb les quals treballem.",
            "sat-search": "Aquí pots cercar una marca específica.",
            "brand-info": "Fes clic en una marca per veure més informació sobre el seu servei tècnic.",
            "sat-info": "Aquí podràs veure la informació de contacte del servei tècnic de la marca seleccionada.",
            "back-button": 'Si desitges tornar a la pàgina anterior, fes clic a "Tornar".',

            // Tour Facturación steps
            "facturacion-header": "En aquesta secció podràs veure la informació sobre la facturació dels teus avisos.",
            "calendar-filter": "Aquí pots filtrar els avisos per data.",
            "cards-filter": "En fer clic a les targetes, podràs veure més informació sobre els avisos, el seu estat i filtrar els avisos de la taula.",
            "accumulated-card": "Per exemple, aquí podràs veure la informació sobre la facturació acumulada dels teus avisos.",
            "dialog-info": "En el diàleg podràs veure la informació detallada dels avisos.",
            "monedero-info": "Aquí podràs veure la informació sobre el saldo del teu moneder.",


            // Tour Fiscal Data steps
            "fiscal-data-header": "En aquesta secció podràs veure la informació fiscal de la teva empresa.",
            "fiscal-data-edit-button": "Fes clic aquí per editar les dades fiscals i per cancel.lar la edició.",
            "fiscal-data-form": "Després de fer clic, podràs editar qualsevol dada del formulari.",
            "fiscal-data-submit": "Un cop hagis completat tots els camps, fes clic a 'Desar' per guardar els canvis.",
            "fiscal-data-contact-button": "Si fas click aquí, podràs veure la informació de contacte de l'empresa.",

            // Tour Resumen steps
            "resumen-header": "En aquesta secció podràs veure el resum dels teus avisos.",
            "calendar-filter": "Aquí pots filtrar els avisos per data.",
            "date-picker": "Pots seleccionar un rang de dates o la mateixa data fent clic dues vegades a la data requerida.",
            "status-filter": "Aquí pots filtrar els avisos per estat.",
            "service-type": "Aquí pots filtrar els avisos per tipus de servei.",
            "customer-name-filter": "Aquí pots cercar un client creat per tu pel seu nom o telèfon.",
            "clean-filter": "Si desitges netejar els filtres, fes clic aquí.",

            // Tour ADD BusINESS steps
            "add-business-header": "En aquesta secció podràs registrar un nou negoci.",
            "add-business-submit": "Fes clic aquí per enviar el formulari i registrar el nou negoci.",

            // Tour ADD USER steps
            "add-user-header": "En aquesta secció podràs registrar un nou usuari.",
            "add-user-submit": "Fes clic aquí per enviar el formulari i registrar el nou usuari.",

            // Error messages
            "NetworkErrorTitle": "Error de xarxa",

            // Settings page

            // Lead Info Dialog
            // "DialogLeadsInProcess": "Avisos pendents",

        }
    }
};

// Load saved language from localStorage or use default
const savedLanguage = localStorage.getItem('i18nextLng') || 'es';

i18n
    .use(initReactI18next) // passes i18n down to react-i18next
    .init({
        resources,
        fallbackLng: "es", // language to use if translations in user language are not available
        lng: savedLanguage, // use saved language or default to Spanish
        // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
        // if you're using a language detector, do not define the lng option

        interpolation: {
            escapeValue: false // react already safes from xss
        }
    });

// Add language change listener to update localStorage
i18n.on('languageChanged', (lng) => {
    localStorage.setItem('i18nextLng', lng);
});

export default i18n;